import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./redux/providers";
import NavBar from "./components/NavBar";
import { AuthContextProvider } from "./context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Spacex Launch Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <NavBar />
          <Providers>{children}</Providers>
        </AuthContextProvider>
      </body>
    </html>
  );
}
